M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 15, Monday 20:56:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-15T20:56:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X0.1522Y0.4337
X0.1522Y0.2763
T2
X1.5872Y0.5147
X1.6272Y0.3147
X1.6671Y0.5147
T0
M30
