M48
; DRILL file {KiCad 7.0.5-0} date 2023 June 02, Friday 14:28:35
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-02T14:28:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X0.1522Y0.4337
X0.1522Y0.2763
T2
X1.5872Y0.5347
X1.6272Y0.3347
X1.6671Y0.5347
T0
M30
